### ISSUE TITLE
Regression introduced when used in nested contexts

### ISSUE THREAD

**Issue by benoitgrelard** [theKashey/react-remove-scroll-bar#57] opened 2024-03-13 16:27 UTC
I believe #55 introduced an issue when `RemoveScrollBar` ends up being used in nested contexts (think via `RemoveScroll` inside nested dialogs, or a popover within a dialog).

Here's a simple reproduction of the issue: https://stackblitz.com/edit/vitejs-vite-wqc3h8?file=src%2FApp.jsx

This is because [this code](https://github.com/theKashey/react-remove-scroll-bar/pull/55/files#diff-e3777a594eaf574004f4baeb03db53d47c1b77b7b92b405cd007fe3e6d8cb4dbR83-R89) removes the `data-scroll-locked` attribute when it the component unmounts, even though there may be other instances that are still mounted.

It all worked fine before because the styles were unscoped.

**Comment by theKashey** [comment] 2024-03-13 20:57
Thank you for the report and finding the root cause.
I know what to do next...

**Comment by JasonColeyNZ** [comment] 2024-03-13 21:39
> Thank you for the report and finding the root cause. I know what to do next...

Watching, I ran into this last night and was pulling my hair out trying to fix this.

**Comment by theKashey** [comment] 2024-03-14 09:57
2.3.6 just released with the fix

**Comment by benoitgrelard** [comment] 2024-03-14 10:16
Thanks for the fix, that's great!
How does it work from the POV of `react-remove-scroll`, does it need a release too with a pinned version of `react-remove-scroll-bar` to `2.3.6`? Or should we lock `react-remoev-scroll-bar` on our side?

**Comment by benoitgrelard** [comment] 2024-03-14 23:41
@theKashey it seems to me the only reliable way to ensure users of `react-remove-scroll` end up for sure not getting the regressed version would be to create a new version there too no?

**Comment by theKashey** [comment] 2024-03-14 23:54
There are two ways to get transitive dependency updated:
- remove the corresponding record in yarn/npm lock file and let be updated, aka "unlock" it. Renovate/Snyk do that
- cause a cascade update for consumers, so eventually developer would be able to control it via explicit package.lock dependency. Renovate/Snyk do that as well

So that's a question - how someone is keeping their packages up to date, manually or via automation.

----

In this particular case I should just __mark the previous version as "broken"__ so automation tools will be triggered to propose update out of bounds, as well as developers installing packages manually will be informed.

**Comment by theKashey** [comment] 2024-03-14 23:54
Not closed until not resolved

**Comment by theKashey** [comment] 2024-03-15 02:10
2.3.5 got deprecated, updates to react-remove-scroll will follow soon....

**Closed by theKashey** 2024-03-15 02:10 UTC
